
(() => {
  const cfg=window.DM_SUPABASE||{};const configured=cfg.url&&cfg.anonKey&&!cfg.url.includes('PASTE_')&&!cfg.anonKey.includes('PASTE_');
  const db=configured&&window.supabase?window.supabase.createClient(cfg.url,cfg.anonKey):null;let records=[],editingImages=[],editingCover='';
  const $=id=>document.getElementById(id);const msg=(id,text,error=false)=>{const e=$(id);e.textContent=text;e.className=`admin-message visible${error?' error':''}`};const clearMsg=id=>$(id).className='admin-message';
  const slugify=s=>String(s||'update').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||`update-${Date.now()}`;
  function pathFromPublicUrl(url){const mark='/storage/v1/object/public/updates-media/';return url&&url.includes(mark)?decodeURIComponent(url.split(mark)[1]):null}
  function showLogin(){ $('adminLogin').style.display='block';$('adminApp').classList.remove('visible') }
  function showApp(user){$('adminLogin').style.display='none';$('adminApp').classList.add('visible');$('adminIdentity').textContent=user.email||user.id}
  async function checkAdmin(session){if(!session){showLogin();return false}const {data,error}=await db.from('update_admins').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!data){showLogin();msg('loginMessage','الحساب مسجل لكنه غير مصرح له بإدارة التحديثات.',true);await db.auth.signOut();return false}showApp(session.user);await loadRecords();return true}
  function resetForm(){ $('updateForm').reset();$('updateId').value='';$('editorTitle').textContent='إضافة تحديث';editingImages=[];editingCover='';$('coverPreview').innerHTML='';$('galleryPreview').innerHTML='';clearMsg('saveMessage') }
  function previewImages(){ $('coverPreview').innerHTML=editingCover?`<figure><img src="${editingCover}" alt=""></figure>`:'';$('galleryPreview').innerHTML=editingImages.map((u,i)=>`<figure><img src="${u}" alt=""><button type="button" data-remove="${i}">×</button></figure>`).join('');$('galleryPreview').querySelectorAll('button').forEach(b=>b.onclick=()=>{editingImages.splice(Number(b.dataset.remove),1);previewImages()}) }
  function editRecord(id){const r=records.find(x=>x.id===id);if(!r)return;$('updateId').value=r.id;$('status').value=r.status;$('category').value=r.category;$('featured').value=String(!!r.featured);$('version').value=r.version||'';$('chapter').value=r.chapter||'';$('slug').value=r.slug||'';$('titleAr').value=r.title_ar||'';$('titleEn').value=r.title_en||'';$('summaryAr').value=r.summary_ar||'';$('summaryEn').value=r.summary_en||'';$('contentAr').value=r.content_ar||'';$('contentEn').value=r.content_en||'';$('tags').value=(r.tags||[]).join(', ');$('publishedAt').value=r.published_at?new Date(r.published_at).toISOString().slice(0,16):'';editingCover=r.cover_image||'';editingImages=[...(r.images||[])];$('editorTitle').textContent='تعديل التحديث';previewImages();scrollTo({top:0,behavior:'smooth'})}
  window.dmEditUpdate=editRecord;
  async function removeRecord(id){if(!confirm('حذف التحديث نهائيًا؟'))return;const r=records.find(x=>x.id===id);const {error}=await db.from('derma_updates').delete().eq('id',id);if(error){alert(error.message);return}const paths=[pathFromPublicUrl(r?.cover_image),...(r?.images||[]).map(pathFromPublicUrl)].filter(Boolean);if(paths.length)await db.storage.from('updates-media').remove(paths);await loadRecords();if($('updateId').value===id)resetForm()}
  window.dmDeleteUpdate=removeRecord;
  function renderList(){const list=$('adminUpdateList');if(!records.length){list.innerHTML='<p>لا توجد تحديثات بعد.</p>';return}list.innerHTML=records.map(r=>`<article class="admin-item"><div class="admin-item-top"><span class="status-pill ${r.status}">${r.status}</span><small>${r.version||''}</small></div><h3>${r.title_ar||r.title_en}</h3><p>${r.chapter||'General'} · ${new Date(r.updated_at).toLocaleDateString('ar-EG')}</p><div class="admin-item-buttons"><button onclick="dmEditUpdate('${r.id}')">تعديل</button><button onclick="dmDeleteUpdate('${r.id}')">حذف</button></div></article>`).join('')}
  async function loadRecords(){const {data,error}=await db.from('derma_updates').select('*').order('updated_at',{ascending:false});if(error){alert(error.message);return}records=data||[];renderList()}
  async function uploadOne(file,prefix){if(!file)return null;if(file.size>5*1024*1024)throw new Error('حجم الصورة يجب ألا يتجاوز 5MB');const ext=(file.name.split('.').pop()||'webp').toLowerCase();const name=`${prefix}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('updates-media').upload(name,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return db.storage.from('updates-media').getPublicUrl(name).data.publicUrl}
  async function save(e){e.preventDefault();clearMsg('saveMessage');$('saveBtn').disabled=true;try{const coverFile=$('coverFile').files[0];if(coverFile)editingCover=await uploadOne(coverFile,'covers');const newGallery=[];for(const file of $('galleryFiles').files)newGallery.push(await uploadOne(file,'gallery'));editingImages.push(...newGallery);const isPublished=$('status').value==='published';const titleEn=$('titleEn').value.trim();const payload={status:$('status').value,category:$('category').value,featured:$('featured').value==='true',version:$('version').value.trim()||null,chapter:$('chapter').value.trim()||null,slug:slugify($('slug').value||titleEn),title_ar:$('titleAr').value.trim(),title_en:titleEn,summary_ar:$('summaryAr').value.trim(),summary_en:$('summaryEn').value.trim(),content_ar:$('contentAr').value.trim(),content_en:$('contentEn').value.trim(),tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),published_at:$('publishedAt').value?new Date($('publishedAt').value).toISOString():(isPublished?new Date().toISOString():null),cover_image:editingCover||null,images:editingImages};const id=$('updateId').value;const q=id?db.from('derma_updates').update(payload).eq('id',id):db.from('derma_updates').insert(payload);const {error}=await q;if(error)throw error;msg('saveMessage','تم حفظ التحديث بنجاح.');await loadRecords();resetForm()}catch(err){console.error(err);msg('saveMessage',err.message||'حدث خطأ أثناء الحفظ.',true)}finally{$('saveBtn').disabled=false}}
  document.addEventListener('DOMContentLoaded',async()=>{if(!db){showLogin();msg('loginMessage','أدخل بيانات Supabase داخل supabase/config.js أولًا.',true);$('loginBtn').disabled=true;return}$('loginForm').onsubmit=async e=>{e.preventDefault();clearMsg('loginMessage');$('loginBtn').disabled=true;const {data,error}=await db.auth.signInWithPassword({email:$('adminEmail').value.trim(),password:$('adminPassword').value});$('loginBtn').disabled=false;if(error){msg('loginMessage',error.message,true);return}await checkAdmin(data.session)};$('logoutBtn').onclick=async()=>{await db.auth.signOut();showLogin()};$('newUpdateBtn').onclick=resetForm;$('cancelEditBtn').onclick=resetForm;$('updateForm').onsubmit=save;$('coverFile').onchange=e=>{const f=e.target.files[0];if(f){const url=URL.createObjectURL(f);$('coverPreview').innerHTML=`<figure><img src="${url}" alt=""></figure>`}};$('galleryFiles').onchange=e=>{const temp=[...e.target.files].map(URL.createObjectURL);$('galleryPreview').innerHTML=[...editingImages,...temp].map(u=>`<figure><img src="${u}" alt=""></figure>`).join('')};const {data}=await db.auth.getSession();await checkAdmin(data.session)});
})();
