
(() => {
  const cfg = window.DM_SUPABASE || {};
  const configured = cfg.url && cfg.anonKey && !cfg.url.includes('PASTE_') && !cfg.anonKey.includes('PASTE_');
  const db = configured && window.supabase ? window.supabase.createClient(cfg.url, cfg.anonKey) : null;
  const categoryLabels = {
    all:{ar:'الكل',en:'All'}, correction:{ar:'تصحيح',en:'Correction'}, content:{ar:'إضافة محتوى',en:'Content'}, treatment:{ar:'تحديث علاجي',en:'Treatment'}, questions:{ar:'أسئلة جديدة',en:'Questions'}, book:{ar:'أخبار الكتاب',en:'Book news'}, website:{ar:'تحديث الموقع',en:'Website'}
  };
  let updates=[], active='all', search='';
  const el=id=>document.getElementById(id);
  const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  function lang(){return window.currentDMLang==='en'?'en':'ar'}
  function text(item,key){return item[`${key}_${lang()}`] || item[`${key}_en`] || item[`${key}_ar`] || ''}
  function dateText(value){if(!value)return '';return new Intl.DateTimeFormat(lang()==='ar'?'ar-EG':'en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value))}
  function parseContent(raw){
    const lines=String(raw||'').split(/\r?\n/);let html='',list=false;
    const close=()=>{if(list){html+='</ul>';list=false}};
    for(const line of lines){const t=line.trim();if(!t){close();continue}if(t.startsWith('## ')){close();html+=`<h3>${escapeHTML(t.slice(3))}</h3>`}else if(t.startsWith('- ')){if(!list){html+='<ul>';list=true}html+=`<li>${escapeHTML(t.slice(2))}</li>`}else{close();html+=`<p>${escapeHTML(t)}</p>`}}close();return html;
  }
  function media(item, cls=''){const src=item.cover_image || (Array.isArray(item.images)&&item.images[0]) || '';return src?`<img class="${cls}" src="${escapeHTML(src)}" alt="${escapeHTML(text(item,'title'))}" loading="lazy">`:''}
  function meta(item){const cat=categoryLabels[item.category]||categoryLabels.content;return `<div class="update-meta"><span>${escapeHTML(cat[lang()])}</span>${item.version?`<span>${escapeHTML(item.version)}</span>`:''}<span>${escapeHTML(dateText(item.published_at||item.created_at))}</span>${item.chapter?`<span>${escapeHTML(item.chapter)}</span>`:''}</div>`}
  function openUpdate(id){const item=updates.find(x=>x.id===id);if(!item)return;const images=(item.images||[]).filter(Boolean);el('updateDialogContent').innerHTML=`${media(item,'update-dialog-cover')}<div class="update-dialog-body"><div class="updates-label">${escapeHTML((categoryLabels[item.category]||categoryLabels.content)[lang()])}</div><h2>${escapeHTML(text(item,'title'))}</h2>${meta(item)}<div class="update-rich">${parseContent(text(item,'content'))}</div>${images.length?`<div class="update-gallery">${images.map(src=>`<img src="${escapeHTML(src)}" alt="" loading="lazy">`).join('')}</div>`:''}</div>`;el('updateDialog').showModal();}
  window.dmOpenUpdate=openUpdate;
  function filtered(){const q=search.trim().toLowerCase();return updates.filter(u=>(active==='all'||u.category===active)&&(!q||[u.title_ar,u.title_en,u.summary_ar,u.summary_en,u.chapter,u.version,(u.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)))}
  function renderFilters(){const cats=['all',...new Set(updates.map(u=>u.category).filter(Boolean))];el('updatesFilters').innerHTML=cats.map(c=>`<button class="updates-filter ${c===active?'active':''}" data-category="${escapeHTML(c)}">${escapeHTML((categoryLabels[c]||{ar:c,en:c})[lang()])}</button>`).join('');el('updatesFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.category;render()})}
  function render(){renderFilters();const data=filtered();el('updatesCount').textContent=String(updates.length).padStart(2,'0');const featured=data.find(u=>u.featured)||data[0];const feature=el('updatesFeatured');if(featured){feature.classList.add('visible');feature.innerHTML=`<div class="updates-featured-media">${media(featured)}</div><div class="updates-featured-body"><div class="updates-label">${escapeHTML((categoryLabels[featured.category]||categoryLabels.content)[lang()])}</div><h2>${escapeHTML(text(featured,'title'))}</h2><p>${escapeHTML(text(featured,'summary'))}</p>${meta(featured)}<button class="update-open" onclick="dmOpenUpdate('${featured.id}')">${lang()==='ar'?'اقرأ التحديث':'Read update'} ↗</button></div>`}else{feature.classList.remove('visible');feature.innerHTML=''}
    const rest=featured?data.filter(u=>u.id!==featured.id):data;el('updatesGrid').innerHTML=rest.map(u=>`<article class="update-card"><div class="update-card-media">${media(u)}</div><div class="update-card-body"><div class="updates-label">${escapeHTML((categoryLabels[u.category]||categoryLabels.content)[lang()])}</div><h3>${escapeHTML(text(u,'title'))}</h3><p>${escapeHTML(text(u,'summary'))}</p>${meta(u)}<button class="update-open" onclick="dmOpenUpdate('${u.id}')">${lang()==='ar'?'التفاصيل':'Details'} ↗</button></div></article>`).join('');el('updatesEmpty').classList.toggle('visible',data.length===0);}
  function showConfigState(){updates=[{id:'setup',category:'website',version:'SETUP',chapter:'Derma-Maze',featured:true,published_at:new Date().toISOString(),title_ar:'مركز التحديثات جاهز للربط',title_en:'The update center is ready to connect',summary_ar:'الصفحة والتصميم جاهزان. بعد ربط Supabase ستظهر التحديثات الحقيقية هنا تلقائيًا.',summary_en:'The page and design are ready. Once Supabase is connected, real updates will appear here automatically.',content_ar:'## الخطوة المتبقية\n- إنشاء مشروع Supabase.\n- تشغيل ملف supabase/setup.sql.\n- وضع رابط المشروع والمفتاح العام داخل supabase/config.js.\n- تسجيل الدخول من صفحة الإدارة وإضافة أول تحديث.',content_en:'## Remaining setup\n- Create a Supabase project.\n- Run supabase/setup.sql.\n- Add the project URL and publishable key to supabase/config.js.\n- Sign in through the admin page and create the first update.'}];render();}
  async function load(){el('updatesLoader').style.display='block';if(!db){el('updatesLoader').style.display='none';showConfigState();return}const {data,error}=await db.from('derma_updates').select('*').eq('status','published').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false});el('updatesLoader').style.display='none';if(error){console.error(error);showConfigState();return}updates=data||[];render();}
  document.addEventListener('DOMContentLoaded',()=>{el('updatesSearch').addEventListener('input',e=>{search=e.target.value;render()});el('updateDialogClose').onclick=()=>el('updateDialog').close();el('updateDialog').addEventListener('click',e=>{if(e.target===el('updateDialog'))el('updateDialog').close()});load()});
  window.addEventListener('dm-language-change',()=>{el('updatesSearch').placeholder=lang()==='ar'?'ابحث داخل التحديثات':'Search updates';render()});
})();
